<?php

/**
* @file
* Handles the creation and display of 3D objects.
*/

/**
* Implements hook_theme
*/
function islandora_sp_3d_theme($existing, $type, $theme, $path) {

    return [
        'islandora_sp_3d_view' => [
            'template' => 'theme/islandora-sp-3d-view',
        ],
    ];
}

/**
 * Implements hook_menu().
 */
function islandora_sp_3d_menu() {

    return [

        'admin/islandora/solution_pack_config/islandora_sp_3d' => [

            'title'            => 'Islandora Solution Pack 3D',
            'description'      => 'Define width/height for Islandora Solution Pack 3D viewer',
            'page callback'    => 'drupal_get_form',
            'page arguments'   => ['islandora_sp_3d_admin'],
            'access arguments' => ['administer site configuration'],
            'file'             => 'includes/admin.form.inc',
            'type'             => MENU_NORMAL_ITEM,
        ],
    ];
}

/**
* Implements hook_islandora_required_objects().
*/
function islandora_sp_3d_islandora_required_objects(IslandoraTuque $connection) {

    $modulePath = drupal_get_path('module', 'islandora_sp_3d');

    // Content Model
    $contentModel         = $connection->repository->constructObject('islandora:sp_3d');
    $contentModel->owner  = 'fedoraAdmin';
    $contentModel->label  = 'Islandora SP 3D Content Model';
    $contentModel->models = 'fedora-system:ContentModel-3.0';

    // DS-COMPOSITE-MODEL Datastream
    $datastream           = $contentModel->constructDatastream('DS-COMPOSITE-MODEL', 'X');
    $datastream->label    = 'DS-COMPOSITE-MODEL';
    $datastream->mimetype = 'application/xml';
    $datastream->setContentFromFile($modulePath . '/xml/islandora_sp_3d_ds_composite_model.xml', false);
    $contentModel->ingestDatastream($datastream);

    // Collection
    $collection         = $connection->repository->constructObject('islandora:sp_3d_collection');
    $collection->owner  = 'fedoraAdmin';
    $collection->label  = '3D collection';
    $collection->models = 'islandora:collectionCModel';
    $collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

    // Collection Policy
    $datastream           = $collection->constructDatastream('COLLECTION_POLICY', 'X');
    $datastream->label    = 'Collection policy';
    $datastream->mimetype = 'application/xml';
    $datastream->setContentFromFile($modulePath . '/xml/islandora_3d_collection_policy.xml', false);
    $collection->ingestDatastream($datastream);

    return [

        'islandora_sp_3d' => [

            'title'   => 'Islandora SP 3D',
            'objects' => [

                $contentModel,
                $collection,
            ],
        ],
    ];
}

/**
* Implements hook_CMODEL_PID_islandora_view_object().
*/
function islandora_sp_3d_islandora_sp_3d_islandora_view_object($object, $page_number, $page_size) {

    $data       = islandora_compound_object_retrieve_compound_info($object);
    $datastream = $object->getDatastream('OBJ');

    if ($datastream && $datastream->mimetype === 'model/vnd.collada+xml' && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $datastream)) {

        $modulePath = drupal_get_path('module', 'islandora_sp_3d');

        drupal_add_js($modulePath . '/js/basename.js');
        drupal_add_js($modulePath . '/js/three.js');
        drupal_add_js($modulePath . '/js/three.collada.loader.js');
        drupal_add_js($modulePath . '/js/three.orbit.controls.js');
        drupal_add_js($modulePath . '/js/app.js');

        $templateData = [

            'pid'    => $object->id,
            'images' => [],
            'url'    => url('islandora/object/' . $object->id . '/datastream/OBJ/view'),
        ];

        if (isset($data['siblings']) && count($data['siblings']) > 0) {

            foreach ($data['siblings_detailed'] as $sibling) {

                $siblingObject = islandora_object_load($sibling['pid']);
                $datastream    = $siblingObject->getDatastream('OBJ');

                if ($datastream && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $siblingObject->getDatastream('OBJ'))) {
                    $templateData['images'][$sibling['title']] = url('islandora/object/' . $siblingObject->id . '/datastream/OBJ/view');
                }
            }
        }

        $templateData['settings'] = [
            'background' => variable_get('islandora_sp_3d_background'),
        ];

        drupal_add_js([
            'islandora_sp_3d' => $templateData,
        ], 'setting');
    }

    return theme('islandora_sp_3d_view', [

        'islandora_object' => $object,
        'max_width'        => variable_get('islandora_sp_3d_width'),
    ]);
}

function islandora_sp_3d_file_mimetype_mapping_alter(&$mapping) {

    $mapping['mimetypes']['dae'] = 'model/vnd.collada+xml';
    $mapping['extensions']['dae'] = 'dae';
}
