<?php

/**
* @file
* Handles the creation and display of 3D objects.
*/

/**
* Implements hook_theme
*/
function islandora_sp_3d_theme($existing, $type, $theme, $path) {

    return [
        'islandora_sp_3d_view' => [
            'template' => 'theme/islandora-sp-3d-view',
        ],
    ];
}

/**
 * Implements hook_menu().
 */
function islandora_sp_3d_menu() {

    return [

        'admin/islandora/solution_pack_config/islandora_sp_3d' => [

            'title'            => 'Islandora Solution Pack 3D',
            'description'      => 'Define width/height for Islandora Solution Pack 3D viewer',
            'page callback'    => 'drupal_get_form',
            'page arguments'   => ['islandora_sp_3d_admin'],
            'access arguments' => ['administer site configuration'],
            'file'             => 'includes/admin.form.inc',
            'type'             => MENU_NORMAL_ITEM,
        ],
    ];
}

/**
* Implements hook_islandora_required_objects().
*/
function islandora_sp_3d_islandora_required_objects(IslandoraTuque $connection) {

    $modulePath = drupal_get_path('module', 'islandora_sp_3d');

    // Content Model
    $contentModel         = $connection->repository->constructObject('islandora:sp_3d');
    $contentModel->owner  = 'fedoraAdmin';
    $contentModel->label  = 'Islandora SP 3D Content Model';
    $contentModel->models = 'fedora-system:ContentModel-3.0';

    // DS-COMPOSITE-MODEL Datastream
    $datastream           = $contentModel->constructDatastream('DS-COMPOSITE-MODEL', 'X');
    $datastream->label    = 'DS-COMPOSITE-MODEL';
    $datastream->mimetype = 'application/xml';
    $datastream->setContentFromFile($modulePath . '/xml/islandora_sp_3d_ds_composite_model.xml', false);
    $contentModel->ingestDatastream($datastream);

    // Collection
    $collection         = $connection->repository->constructObject('islandora:sp_3d_collection');
    $collection->owner  = 'fedoraAdmin';
    $collection->label  = '3D collection';
    $collection->models = 'islandora:collectionCModel';
    $collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

    // Collection Policy
    $datastream           = $collection->constructDatastream('COLLECTION_POLICY', 'X');
    $datastream->label    = 'Collection policy';
    $datastream->mimetype = 'application/xml';
    $datastream->setContentFromFile($modulePath . '/xml/islandora_3d_collection_policy.xml', false);
    $collection->ingestDatastream($datastream);

    return [

        'islandora_sp_3d' => [

            'title'   => 'Islandora SP 3D',
            'objects' => [

                $contentModel,
                $collection,
            ],
        ],
    ];
}

/**
* Implements hook_CMODEL_PID_islandora_view_object().
*/
function islandora_sp_3d_islandora_sp_3d_islandora_view_object($object, $page_number, $page_size) {

    module_load_include('inc', 'islandora_sp_3d', 'includes/DaeFetcher');

    $fetcher    = new DaeFetcher($object);
    $datastream = $fetcher->getDatastream();

    if ($datastream) {

        $modulePath = drupal_get_path('module', 'islandora_sp_3d');

        drupal_add_js($modulePath . '/js/threejs/three.js');
        drupal_add_js($modulePath . '/js/threejs/three.collada.loader.js');
        drupal_add_js($modulePath . '/js/threejs/three.orbit.controls.js');
        drupal_add_js($modulePath . '/js/ColladaArchiveLoader/ColladaArchiveLoader.js');
        drupal_add_js($modulePath . '/js/jszip/jszip.min.js');
        drupal_add_js($modulePath . '/js/pako/pako_deflate.min.js');
        drupal_add_js($modulePath . '/js/pako/pako_inflate.min.js');
        drupal_add_js($modulePath . '/js/pako/pako.min.js');
        drupal_add_js($modulePath . '/js/basename.js');
        drupal_add_js($modulePath . '/js/app.js');

        $data = [

            'url'      => url('islandora/object/' . $datastream->parent->id . '/datastream/OBJ/view'),
            'mime'     => $datastream->mimetype,
            'textures' => $fetcher->getTextures(),
        ];

        $data['settings'] = [
            'background' => variable_get('islandora_sp_3d_background'),
	    'scale' => variable_get('islandora_sp_3d_scale'),
	    'minDistance' => variable_get('islandora_sp_3d_minDistance'),
	    'maxDistance' => variable_get('islandora_sp_3d_maxDistance'),
        ];

        drupal_add_js([
            'islandora_sp_3d' => $data,
        ], 'setting');
    }

    return theme('islandora_sp_3d_view', [

        'islandora_object' => $object,
        'max_width'        => variable_get('islandora_sp_3d_width'),
    ]);
}

function islandora_sp_3d_file_mimetype_mapping_alter(&$mapping) {

    $mapping['mimetypes']['dae']   = 'model/vnd.collada+xml';
    $mapping['mimetypes']['zae']   = 'application/collada-zipped';
    $mapping['mimetypes']['fbx']   = 'application/octet-stream';
    $mapping['mimetypes']['OSGB']  = 'application/octet-stream';

    $mapping['extensions']['dae']  = 'dae';
    $mapping['extensions']['zae']  = 'zae';
    $mapping['extensions']['fbx']  = 'fbx';
    $mapping['extensions']['OSGB'] = 'OSGB';
}

function islandora_sp_3d_islandora_sp_3d_islandora_ingest_steps() {

    return [

        'islandora_sp_3d' => [

            'weight'  => 10,
            'type'    => 'form',
            'form_id' => 'islandora_sp_3d_3d_upload',
            'module'  => 'islandora_sp_3d',
            'file'    => 'includes/3d_upload.form.inc',
        ],
    ];
}
